[package]
name = "rust-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
mime = "0.3.17"
signal-hook = "0.3.18"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6.6", features = ["fs"] }
