[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
ctrlc = "3.5.1"
env_logger = "0.11.8"
futures = "0.3.31"
log = "0.4.28"
reqwest = "0.12.24"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
