services:
  benchmark-runner:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../assets:/assets
      - .:/app
      - ../webservers:/webservers
    networks:
      - benchmark
    ulimits:
      nofile:
        soft: 50000
        hard: 50000

networks:
  benchmark:
    driver: bridge
